apiVersion: v1
kind: Service
metadata:
  name: unitconverter-service
spec:
  selector:
    app: unitconverter
  type: NodePort
  ports:
  - port: 5002
    targetPort: 5002 
    nodePort: 30000
    protocol: TCP